from .octopozt_ad_system    import NODE_CLASS_MAPPINGS,          NODE_DISPLAY_NAME_MAPPINGS
from .octopozt_audio_mixer  import NODE_CLASS_MAPPINGS_MIXER,    NODE_DISPLAY_NAME_MAPPINGS_MIXER
from .octopozt_audio_analyzer import NODE_CLASS_MAPPINGS_ANALYZER, NODE_DISPLAY_NAME_MAPPINGS_ANALYZER

NODE_CLASS_MAPPINGS        = {**NODE_CLASS_MAPPINGS, **NODE_CLASS_MAPPINGS_MIXER, **NODE_CLASS_MAPPINGS_ANALYZER}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **NODE_DISPLAY_NAME_MAPPINGS_MIXER, **NODE_DISPLAY_NAME_MAPPINGS_ANALYZER}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
