from .octopozt_ad_system      import NODE_CLASS_MAPPINGS,            NODE_DISPLAY_NAME_MAPPINGS
from .octopozt_audio_mixer    import NODE_CLASS_MAPPINGS_MIXER,      NODE_DISPLAY_NAME_MAPPINGS_MIXER
from .octopozt_audio_analyzer import NODE_CLASS_MAPPINGS_ANALYZER,   NODE_DISPLAY_NAME_MAPPINGS_ANALYZER
from .octopozt_automix        import NODE_CLASS_MAPPINGS_AUTOMIX,    NODE_DISPLAY_NAME_MAPPINGS_AUTOMIX
from .octopozt_eleven_music   import NODE_CLASS_MAPPINGS_ELEVEN,     NODE_DISPLAY_NAME_MAPPINGS_ELEVEN
from .octopozt_suno           import NODE_CLASS_MAPPINGS_SUNO,       NODE_DISPLAY_NAME_MAPPINGS_SUNO
from .octopozt_musicgen       import NODE_CLASS_MAPPINGS_MUSICGEN,   NODE_DISPLAY_NAME_MAPPINGS_MUSICGEN
from .octopozt_png_to_hdri    import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_HDRI, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_HDRI

NODE_CLASS_MAPPINGS        = {**NODE_CLASS_MAPPINGS, **NODE_CLASS_MAPPINGS_MIXER, **NODE_CLASS_MAPPINGS_ANALYZER, **NODE_CLASS_MAPPINGS_AUTOMIX, **NODE_CLASS_MAPPINGS_ELEVEN, **NODE_CLASS_MAPPINGS_SUNO, **NODE_CLASS_MAPPINGS_MUSICGEN, **NODE_CLASS_MAPPINGS_HDRI}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **NODE_DISPLAY_NAME_MAPPINGS_MIXER, **NODE_DISPLAY_NAME_MAPPINGS_ANALYZER, **NODE_DISPLAY_NAME_MAPPINGS_AUTOMIX, **NODE_DISPLAY_NAME_MAPPINGS_ELEVEN, **NODE_DISPLAY_NAME_MAPPINGS_SUNO, **NODE_DISPLAY_NAME_MAPPINGS_MUSICGEN, **NODE_DISPLAY_NAME_MAPPINGS_HDRI}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
